# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testAAA' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'TFHpple'
  pod 'AFNetworking', '~> 4.0'
  pod 'WJTKit'
  pod 'YYModel'
  pod 'JQFMDB'
#  pod 'YYImage'
#  pod 'YYImage/WebP'
end
